name: Testing triggers

on:
  push:
    branches:
      - "releases/**"
  create:
    branches:
      - "releases/**"
  workflow_dispatch:

jobs:
  do-something:
    name: Doing something
    runs-on: ubuntu-latest

    # When creating a branch, both the 'push' and 'create' triggertypes trigger a workflow run.
    # To avoid having to pay for an additional run, adding this will cancel one of the workflow runs.
    concurrency:
      group: ${{ github.head_ref }}-init
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Event type: ${{ github.event_name }}"
        run: |
          echo "Event type: ${{ github.event_name }}"

      - name: Print GitHub event action
        run: |
          echo "Event action: ${{ github.event.action }}"

      - name: Writing to screen
        run: echo "Testing some triggers in a workflow"