name: Testing triggers

on:
  push:
    branches:
      - "releases/**"
  create:
    branches:
      - "releases/**"
  workflow_dispatch:

jobs:
  do-something:
    name: Doing something
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Writing to screen
        run: echo "Testing some triggers in a workflow"